#!/usr/bin/env python3
"""
Generates src/shaders/gto/gto_int_hermite.slang: one straight-line function per Hermite order L
that evaluates the potential of one gaussian of md_gto_int.h,

    V = sum_{t+u+v <= L} h[i(t,u,v)] * R^0_tuv(X)

given X = P - C and s[n] = (-2p)^n F_n(p |X|^2). The McMurchie-Davidson recursion

    R^n_{t+1,u,v} = t R^{n+1}_{t-1,u,v} + X R^{n+1}_{t,u,v}     (likewise u, v)

is unrolled completely, so every index is a constant and each order compiles to its own minimal
register footprint. i(t,u,v) is the coefficient order of md_gto_int.h: degree ascending, then t
descending, then u descending - the same closed form as herm_idx() in md_gto_int.c.

Run from the repository root:  python3 tools/gen_gto_int_hermite.py
"""
import os
import sys

MAX_ORDER = 8   # MD_GTO_INT_MAX_ORDER = 2 * MD_GTO_MAX_ANGULAR_MOMENTUM


def degree_order(deg):
    for t in range(deg, -1, -1):
        for u in range(deg - t, -1, -1):
            yield t, u, deg - t - u


def herm_idx(t, u, v):
    n = t + u + v
    return n * (n + 1) * (n + 2) // 6 + (n - t) * (n - t + 1) // 2 + (n - t - u)


def name(lvl, t, u, v):
    return f"r{lvl}_{t}{u}{v}" if max(t, u, v) < 10 else f"r{lvl}_{t}_{u}_{v}"


def gen_order(L):
    lines = []
    lines.append(f"float gto_int_hermite_L{L}(float x, float y, float z, float s[GTO_INT_NS], float* h, uint o) {{")
    for lvl in range(L, -1, -1):
        top = L - lvl
        for deg in range(0, top + 1):
            for (t, u, v) in degree_order(deg):
                if deg == 0:
                    rhs = f"s[{lvl}]"
                else:
                    if t > 0:
                        a, k, x = (t - 1, u, v), t - 1, "x"
                        b = (t - 2, u, v)
                    elif u > 0:
                        a, k, x = (t, u - 1, v), u - 1, "y"
                        b = (t, u - 2, v)
                    else:
                        a, k, x = (t, u, v - 1), v - 1, "z"
                        b = (t, u, v - 2)
                    rhs = f"{x} * {name(lvl + 1, *a)}"
                    if k > 0:
                        rhs += f" + {float(k):.1f}f * {name(lvl + 1, *b)}"
                lines.append(f"    const float {name(lvl, t, u, v)} = {rhs};")
    terms = []
    for deg in range(0, L + 1):
        for (t, u, v) in degree_order(deg):
            i = herm_idx(t, u, v)
            terms.append(f"h[o + {i}u] * {name(0, t, u, v)}")
    lines.append(f"    float acc = {terms[0]};")
    for term in terms[1:]:
        lines.append(f"    acc += {term};")
    lines.append("    return acc;")
    lines.append("}")
    return "\n".join(lines)


def main():
    root = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
    out = os.path.join(root, "src", "shaders", "gto", "gto_int_hermite.slang")
    parts = [
        "// gto_int_hermite.slang",
        "// GENERATED by tools/gen_gto_int_hermite.py - do not edit, re-run the script.",
        "//",
        "// gto_int_hermite_L<L>(x, y, z, s, h, o) = sum_{t+u+v<=L} h[o + i] R^0_tuv(X)",
        "//   X = (x, y, z) = P - C, s[n] = (-2p)^n F_n(p |X|^2), h[o..] = the gaussian's coefficients",
        "//   in the order of md_gto_int.h. Unrolled so each order has its own register footprint.",
        "",
        "#ifndef GTO_INT_HERMITE_SLANG",
        "#define GTO_INT_HERMITE_SLANG",
        "",
        f"#define GTO_INT_NS {MAX_ORDER + 1}",
        "",
    ]
    for L in range(MAX_ORDER + 1):
        parts.append(gen_order(L))
        parts.append("")
    parts.append("#endif")
    text = "\n".join(parts) + "\n"
    with open(out, "w", newline="\n") as f:
        f.write(text)
    print(f"wrote {out} ({text.count(chr(10))} lines)")


if __name__ == "__main__":
    sys.exit(main())
