name: Ubuntu 22.04 (GCC 11)

on: [push]

env:
  BUILD_TYPE: RelWithDebInfo
  VCPKG_DEFAULT_TRIPLET: x64-linux
  VCPKG_GIT_COMMIT_ID: 216bb6975d5cccd35c27a14fb39acec3ae0e8285
  VCPKG_DEFAULT_BINARY_CACHE: ${{ github.workspace }}/.vcpkg/binary-cache
  VCPKG_BINARY_SOURCES: "clear;default,readwrite"

jobs:
    ci:
        runs-on: ubuntu-22.04
        permissions:
          contents: read
        steps:
          - uses: actions/checkout@v4

          - name: Restore vcpkg binary cache
            uses: actions/cache@v4
            with:
              path: ${{ env.VCPKG_DEFAULT_BINARY_CACHE }}
              key: vcpkg-${{ github.workflow }}-${{ env.VCPKG_DEFAULT_TRIPLET }}-${{ env.VCPKG_GIT_COMMIT_ID }}-${{ hashFiles('vcpkg.json') }}
              restore-keys: |
                vcpkg-${{ github.workflow }}-${{ env.VCPKG_DEFAULT_TRIPLET }}-${{ env.VCPKG_GIT_COMMIT_ID }}-

          - name: Setup Vcpkg
            uses: lukka/run-vcpkg@v11
            with:
              vcpkgGitCommitId: ${{ env.VCPKG_GIT_COMMIT_ID }}

          - name: Clone MDLIB
            run: git submodule update --init --recursive

          - name: Cmake Version
            run: cmake --version

          - name: Create Build Environment
            run: cmake -E make_directory ${{github.workspace}}/build

          - name: Configure CMake
            shell: bash
            working-directory: ${{github.workspace}}/build
            run: cmake -DCMAKE_BUILD_TYPE=$BUILD_TYPE -DMD_ENABLE_VLX=ON -DMD_FORCE_ASSERTIONS=ON $GITHUB_WORKSPACE

          - name: Build
            working-directory: ${{github.workspace}}/build
            shell: bash
            run: cmake --build . --config $BUILD_TYPE

          - name: Test
            working-directory: ${{github.workspace}}/build
            shell: bash
            run: ctest -C $BUILD_TYPE --rerun-failed --output-on-failure
          
          - name: Setup upterm session
            uses: lhotari/action-upterm@v1
            if: ${{ failure() }}
            with: 
              ## limits ssh access and adds the ssh public key for the user which triggered the workflow
              limit-access-to-actor: false
              ## If no one connects after 5 minutes, shut down server.
              wait-timeout-minutes: 5